site_name: Apex Agente
site_author: jo-project
site_description: >-
  Unlock Your Network's Potential with Apex Agente
repo_name: ApexAgente
theme:
  logo: assets/icon.png
  favicon: assets/logo.png
  name: dracula
  custom_dir: dracula/.overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view
    - announce.dismiss
  language: en

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ApexAgante
      name: ApexAgante on Github

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ApexAgante
      repo: ApexAgente
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/ApexAgante"  target="_blank" rel="noopener">Apex Agante</a>
